// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_response_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Customer _$CustomerFromJson(Map<String, dynamic> json) => Customer(
      id: (json['id'] as num?)?.toInt(),
      accountRef: json['AccountRef'] as String?,
      address1: json['Address1'] as String?,
      address2: json['Address2'] as String?,
      address3: json['Address3'] as String?,
      address4: json['Address4'] as String?,
      address5: json['Address5'] as String?,
      cAddress1: json['CAddress1'] as String?,
      cAddress2: json['CAddress2'] as String?,
      cAddress3: json['CAddress3'] as String?,
      cAddress4: json['CAddress4'] as String?,
      cAddress5: json['CAddress5'] as String?,
      contactName: json['ContactName'] as String?,
      countryCode: json['CountryCode'] as String?,
      createdDate: json['CreatedDate'] as String?,
      dateAccountOpened: json['DateAccountOpened'] as String?,
      discountPercentage: (json['DiscountPercentage'] as num?)?.toDouble(),
      email: json['Email'] as String?,
      fax: json['Fax'] as String?,
      isCostcutter: json['IsCostcutter'] as bool?,
      isDeleted: json['IsDeleted'] as bool?,
      isHenderson: json['IsHenderson'] as bool?,
      isMessageEnabled: json['IsMessageEnabled'] as bool?,
      isMusgrave: json['IsMusgrave'] as bool?,
      isPredictionEnable: json['IsPredictionEnable'] as bool?,
      isTemplateEnable: json['IsTemplateEnable'] as bool?,
      message: json['Message'] as String?,
      modifiedDate: json['ModifiedDate'] as String?,
      name: json['Name'] as String?,
      telephone: json['Telephone'] as String?,
      telephone2: json['Telephone2'] as String?,
      webAddress: json['WebAddress'] as String?,
    );

Map<String, dynamic> _$CustomerToJson(Customer instance) => <String, dynamic>{
      'id': instance.id,
      'AccountRef': instance.accountRef,
      'Address1': instance.address1,
      'Address2': instance.address2,
      'Address3': instance.address3,
      'Address4': instance.address4,
      'Address5': instance.address5,
      'CAddress1': instance.cAddress1,
      'CAddress2': instance.cAddress2,
      'CAddress3': instance.cAddress3,
      'CAddress4': instance.cAddress4,
      'CAddress5': instance.cAddress5,
      'ContactName': instance.contactName,
      'CountryCode': instance.countryCode,
      'CreatedDate': instance.createdDate,
      'DateAccountOpened': instance.dateAccountOpened,
      'DiscountPercentage': instance.discountPercentage,
      'Email': instance.email,
      'Fax': instance.fax,
      'IsCostcutter': instance.isCostcutter,
      'IsDeleted': instance.isDeleted,
      'IsHenderson': instance.isHenderson,
      'IsMessageEnabled': instance.isMessageEnabled,
      'IsMusgrave': instance.isMusgrave,
      'IsPredictionEnable': instance.isPredictionEnable,
      'IsTemplateEnable': instance.isTemplateEnable,
      'Message': instance.message,
      'ModifiedDate': instance.modifiedDate,
      'Name': instance.name,
      'Telephone': instance.telephone,
      'Telephone2': instance.telephone2,
      'WebAddress': instance.webAddress,
    };
